Repository radical-doubting/anikultura-frontend, pull requests merged in 2022-10, with the labels that each got.

#25 [Fix] Improve UI design of report verification status (#22)
  src/app/home/home.page.html
  src/app/home/home.page.scss
Labels: enhancement

#27 [Fix] Fix farmer report modal and home page translations
  src/app/home/home.page.html
  src/app/home/home.page.ts
  src/app/home/modal/submit-report-modal.page.html
  src/app/home/modal/submit-report-modal.page.ts
Labels: fix

#32 [Chore] Added, submitted review status translations in the homepage and JSON …
  src/app/home/home.page.html
  src/assets/i18n/ceb.json
  src/assets/i18n/en.json
  src/assets/i18n/fil_PH.json
Labels: chore
